// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJlwJhrZwcbUHBSpMBtWQEKKV9Y80lqgc',
    appId: '1:161661897387:web:b6dfa53e48f6c06f6645ee',
    messagingSenderId: '161661897387',
    projectId: 'chat-app-d51a5',
    authDomain: 'chat-app-d51a5.firebaseapp.com',
    storageBucket: 'chat-app-d51a5.appspot.com',
    measurementId: 'G-29Y4FR1KCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZc5E0IHDYg7Lwlth4fNuyFdVeF13MDI',
    appId: '1:161661897387:android:c58d634d14501a986645ee',
    messagingSenderId: '161661897387',
    projectId: 'chat-app-d51a5',
    storageBucket: 'chat-app-d51a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFitLl1tezseqsfBsKzLOV7chIFEDYAg',
    appId: '1:161661897387:ios:1edab94b46ba79c36645ee',
    messagingSenderId: '161661897387',
    projectId: 'chat-app-d51a5',
    storageBucket: 'chat-app-d51a5.appspot.com',
    iosClientId: '161661897387-1vi9nnnp0n00856qiicetuup3emav026.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYFitLl1tezseqsfBsKzLOV7chIFEDYAg',
    appId: '1:161661897387:ios:b8c3e3b1459e134a6645ee',
    messagingSenderId: '161661897387',
    projectId: 'chat-app-d51a5',
    storageBucket: 'chat-app-d51a5.appspot.com',
    iosClientId: '161661897387-j90jemvmf7u0lg5g0ntemp3dl5bognnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
